version: "3.9"

services:
  web:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql://urbvbmxcu9morjp7:E8CMsE7fDdxDHPCcPOh9@bqm4pgy45ritx2m2zkgn-mysql.services.clever-cloud.com:3306/bqm4pgy45ritx2m2zkgn
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: dbname
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
